#event_homepage:
#    pattern:     /hello/{name}
#    defaults: { _controller: EventBundle:Default:index }


event_homepage:
    path:     /hello/{name}
    defaults: { _controller: EventBundle:Default:index }